- name: variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Trainer: "joindevops"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, Duration {{Duration}}."